### ISSUE TITLE
Hi. Does this work?

### ISSUE THREAD

**Issue by smolinari** [llong2195/nest-hyper-express#1]
Hi,

I was wondering, does this actually work? I figured I'd ask to see if I get a response, before I dig into it.

Scott

**Comment by smolinari** [comment]
Ok. I've put together a test app and it works. I noticed there are some features missing. I'm going to continue on this work. I'll be sure to give you credit for the initial effort. Thanks!

Scott

**Comment by llong2195** [comment]
Oh, wow, thank you so much.
Now that I see this, I'm glad it can bring something positive

**Comment by smolinari** [comment]
Yeah, unfortunately. Hyper-express is far from having feature parity to Express and my attempts to get Kartik to work on the next feature-parity version failed. He said, maybe sometime. 

https://github.com/kartikk221/hyper-express/issues/244

Scott
