### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jk89** [llong2195/nest-hyper-express#197]
Hi what license is this under? You code has no LICENSE file and the README although it implies its MIT seems to be the default nest.js generated README. The package.json says UNLICENSED. I Just want to check explicitly that it is permissively liscensed. I would like to fork and work on a node single executable application version (with a simple fork of uWebsockets.js and hyper-express) so I can make binaries of my nest.js project using it. Good work! Let me know.

**Comment by llong2195** [comment]
> Hi what license is this under? You code has no LICENSE file and the README although it implies its MIT seems to be the default nest.js generated README. The package.json says UNLICENSED. I Just want to check explicitly that it is permissively liscensed. I would like to fork and work on a node single executable application version (with a simple fork of uWebsockets.js and hyper-express) so I can make binaries of my nest.js project using it. Good work! Let me know.

Hello. Thank you for your interest in this project. Feel free to do whatever you like with it.
